### ISSUE TITLE
Requesting alternate licenses for `x-util.lua`

### ISSUE THREAD

**Issue by sparr** [tburrows13/LunarLandings#12]
This is a great library. Would you be willing to also license it under the MIT license for use in other mods that use that license instead of GPL?

**Comment by tburrows13** [comment]
Yes, I'm happy to dual-licence it under MIT. Lots of it came from BZ mods, which are already MIT, and some of it came from @RedRafe, so I'd need his permission too.

**Comment by RedRafe** [comment]
Happy to MIT it 👍
